package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Visual-Regression-Tracker test")
    void generatedTest() {
        step("open repo https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker", () -> {
            // todo
        });

        step("set star", () -> {
            // todo
        });

        step("verify star", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker'", () ->
            open("https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker"));

        step("Checking that the page title has is 'GitHub - Visual-Regression-Tracker/Visual-Regression-Tracker: Backend and Frontend application for tracking differences via image comparison'", () -> {
            String expectedTitle = "GitHub - Visual-Regression-Tracker/Visual-Regression-Tracker: Backend and Frontend application for tracking differences via image comparison";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}